import type { VariableItem } from "./types";

export const INITIAL_VARIABLES: VariableItem[] = [
	{
		id: "var-1",
		name: "Production Database",
		type: "credential",
		value: "postgresql://postgres:secret_pass_123@db.studio.internal:5432/main",
		clientVisibility: false,
		notesTeam: "Direct connection URI for production PostgreSQL cluster.",
		notesClient: "",
		createdAt: "2026-08-01",
	},
	{
		id: "var-2",
		name: "Figma Design System",
		type: "link",
		value: "https://www.figmaballs.com/file/asceoft-studio-tokens-v4-master",
		clientVisibility: true,
		notesTeam: "Main component library and prototype boards.",
		notesClient: "Feel free to inspect assets and leave comments on the prototype.",
		createdAt: "2026-08-02",
	},
	{
		id: "var-3",
		name: "Frontend Monorepo",
		type: "repository",
		value: "ah@archershub.com:asceoft-studio/client-stage-gate-portal.git",
		clientVisibility: true,
		notesTeam: "Ensure CI tests pass before opening pull requests to main.",
		notesClient: "Client repository access for deployment auditing.",
		createdAt: "2026-08-03",
	},
	{
		id: "var-4",
		name: "Stripe API Secret",
		type: "credential",
		value: "sk_live_51Ny8X2L89Zb01qPwR92kxLmnOpQrStUvWxYz",
		clientVisibility: false,
		notesTeam: "Production secret key. Do not share outside owner tier.",
		notesClient: "",
		createdAt: "2026-08-04",
	},
	{
		id: "var-5",
		name: "Staging Preview URL",
		type: "link",
		value: "https://staging-preview.asceoft.dev/v2",
		clientVisibility: true,
		notesTeam: "Auto-deployed on merge to develop branch.",
		notesClient: "Use this live URL for gate review approvals.",
		createdAt: "2026-08-05",
	},
];